chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('comunity.urls')),
    path('', include('posts.urls')),
    path('', include('comments.urls')),

    path('login/', auth_views.LoginView.as_view(), name='login'),
     
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'},
         name='logout')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.urls import path
from comments.views import CommentsByPost, CommentCreateView
app_name ="comment"

urlpatterns = [
    path('comments/<shorname>/', CommentsByPost.as_view(), name='comentarios'),
    path('comment/crear/', CommentCreateView.as_view(), name='crear_comentario'),

]

comunity/urls.py
from django.urls import path
from comunity.views import CommunityList, CommunityDetail, CommunityCreateView

app_name = "community"

urlpatterns = [
    path('home/', CommunityList.as_view(), name='index'),
    path('comunidad/detail/<str:slug>', CommunityDetail.as_view(), name='comunidad_detail'),
    path('comunidad/crear', CommunityCreateView.as_view(), name='comunidad_crear'),
]

core/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from rest_framework.routers import DefaultRouter
from core.api import MessageModelViewSet, UserModelViewSet

router = DefaultRouter()
router.register(r'message', MessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')
app_name ="core"
urlpatterns = [
    path(r'api/v1/', include(router.urls)),

    path('', login_required(
        TemplateView.as_view(template_name='core/chat.html')), name='home'),

]

posts/urls.py
from django.urls import path
from posts.views import PostByCommunity, PostCreateView
app_name ="post"

urlpatterns = [
    path('comunidades/<shorname>/', PostByCommunity.as_view(), name='post_comunidad'),
    path('post/crear/', PostCreateView.as_view(), name='crer_post'),

]

users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
    path(
        'user-verification/<pk>/', 
        views.CodeVerificationView.as_view(),
        name='user-verification',
    ),
    path(
        'profile/<shorname>/',
        views.UserProfileListView.as_view(),
        name='user-verification',
    ),
]

comments/models.py
from django.db import models
from django.db.models import CASCADE
from users.models import User
from posts.models import Post


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=CASCADE, null=True)

core/models.py
# from django.contrib.auth.models import User
from users.models import User
from django.db.models import (Model, TextField, DateTimeField, ForeignKey,
                              CASCADE)

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer


class MessageModel(Model):
    """
    This class represents a chat message. It has a owner (user), timestamp and
    the message body.

    """
    user = ForeignKey(User, on_delete=CASCADE, verbose_name='user',
                      related_name='from_user', db_index=True)
    recipient = ForeignKey(User, on_delete=CASCADE, verbose_name='recipient',
                           related_name='to_user', db_index=True)
    timestamp = DateTimeField('timestamp', auto_now_add=True, editable=False,
                              db_index=True)
    body = TextField('body')

    def __str__(self):
        return str(self.id)

    def characters(self):
        """
        Toy function to count body characters.
        :return: body's char number
        """
        return len(self.body)

    def notify_ws_clients(self):
        """
        Inform client there is a new message.
        """
        notification = {
            'type': 'recieve_group_message',
            'message': '{}'.format(self.id)
        }

        channel_layer = get_channel_layer()
        print("user.id {}".format(self.user.id))
        print("user.id {}".format(self.recipient.id))

        async_to_sync(channel_layer.group_send)("{}".format(self.user.id), notification)
        async_to_sync(channel_layer.group_send)("{}".format(self.recipient.id), notification)

    def save(self, *args, **kwargs):
        """
        Trims white spaces, saves the message and notifies the recipient via WS
        if the message is new.
        """
        new = self.id
        self.body = self.body.strip()  # Trimming whitespaces from the body
        super(MessageModel, self).save(*args, **kwargs)
        if new is None:
            self.notify_ws_clients()

    # Meta
    class Meta:
        app_label = 'core'
        verbose_name = 'message'
        verbose_name_plural = 'messages'
        ordering = ('-timestamp',)

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ('pass','user')

        widgets = {

            'description':forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese una descripcion',
                }
            ),
            'slug':forms.TextInput(
                attrs = {
                    'class':'form-control',
                    'placeholder': 'Ingrese su mensaje',
                }
            ),
        }

comments/api/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend

from comments.models import Comment
from comments.api.serializers import CommentSerializer
from comments.api.permissions import IsOwnerOrReadAndCreateOnly


class CommentApiViewSet(ModelViewSet):
    permission_classes = [IsOwnerOrReadAndCreateOnly]
    serializer_class = CommentSerializer
    queryset = Comment.objects.all()
    filter_backends = [OrderingFilter, DjangoFilterBackend]
    ordering = ['-created_at']
    filterset_fields = ['post']

comments/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Comment
from .forms import CommentForm
from django.urls import reverse_lazy
import datetime

# Create your views here.


class CommentsByPost(ListView):
    template_name = "core/comments.html"
    model = Comment
    context_object_name = "comments"

    def get_queryset(self):
        # el codigo que yo queira
        area = self.kwargs['shorname']
        lista = Comment.objects.filter(
            post__slug=area
        ).order_by('-created_at')
        print(lista)
        return lista

class CommentCreateView(CreateView):
    template_name = "comment/create_comment.html"
    model = Comment
    form_class = CommentForm
    success_url = reverse_lazy('community:index')

    def form_valid(self, form):
        print(self.request.user)
        #logica del proceso
        comunidad = form.save(commit=False)
        # empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        # comunidad.slug = comunidad.title.replace(" ", "-")
        comunidad.user = self.request.user
        comunidad.save()
        return super(CommentCreateView, self).form_valid(form)

templates/core/comments.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Casinal</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- owl carousel style -->
   <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{%  static 'css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{%  static 'images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{%  static 'css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="{%  static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{%  static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
</head>

<body>
   <!--header section start -->
   <div class="header_section">
      <div class="header_bg">
         <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="{% url 'community:index' %}"><img src="{%  static 'images/logo.png ' %}"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'community:index' %} ">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="about.html">Comunidades</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="services.html">Noticias</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                  </ul>
                  <div class="call_section">
                     <ul>
                        <li><a href="#"><img src="{%  static 'images/fb-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/twitter-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/linkedin-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/instagram-icon.png' %}"></a></li>
                        <li>
                          {% if not user.is_anonymous %}
                        <a href="" class="btn">Perfil</a></li>
                    {% else %}
                                    <div class="header-btn d-none f-right d-lg-block">
                                    <a href="{% url 'users_app:user-register'%}" class="btn head-btn1">Registrarse</a>
                                    <a href="{% url 'users_app:user-login' %}" class="btn head-btn2">Acceder</a></li>
                    {% endif %}
                        <div class="donate_bt"><a href="#"><img src="{%  static 'images/search-icon.png' %}"></a></div>
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
      </div>
      <!--banner section start -->
      <div class="banner_section layout_padding">
         <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Espacio de tu artistas</h1>
                              <p class="banner_text">Ultimas actualziaciones</p>
                              <div class="btn_main">
                                   {% if user.is_anonymous %}
                                       <div class="about_bt active"><a href="{% url 'users_app:user-login' %}">Login</a></div>
                                 <div class="quote_bt"><a href="{% url 'users_app:user-register' %}">Registrarse </a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="{% url 'comment:crear_comentario' %}">Crear Comentario</a></div>
                                 <div class="quote_bt"><a href="#">Explorar </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Red social de comunidades de tus artistas</h1>
                              <p class="banner_text">El mejor seguimiento de todos tus artistas favoritos en solo lugar</p>
                              <div class="btn_main">
                                 {% if user.is_anonymous %}
                                       <div class="about_bt active"><a href="{% url 'users_app:user-login' %}">Login</a></div>
                                 <div class="quote_bt"><a href="{% url 'users_app:user-register' %}">Registrarse </a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="{% url 'comment:crear_comentario' %}">Crear Comentario</a></div>
                                 <div class="quote_bt"><a href="#">Explorar </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Red social de comunidades de tus artistas</h1>
                              <p class="banner_text">El mejor seguimiento de todos tus artistas favoritos en solo lugar</p>
                              <div class="btn_main">
                                 {% if user.is_anonymous %}
                                       <div class="about_bt active"><a href="{% url 'users_app:user-login' %}">Login</a></div>
                                 <div class="quote_bt"><a href="{% url 'users_app:user-register' %}">Registrarse </a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="{% url 'comment:crear_comentario' %}">Crear Comentario</a></div>
                                 <div class="quote_bt"><a href="#">Explorar </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
               <i class="fa fa-arrow-left" style="font-size:24px"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
               <i class="fa fa-arrow-right" style="font-size:24px"></i>
            </a>
         </div>
      </div>
      <!--banner section end -->
   </div>
      <!--banner section start -->
<section class="blog-list px-3 py-5 p-md-5"> Comentarios
    {% for comment in comments %}

		    <div class="container">
			    <div class="item mb-5">
				    <div class="media">
{#					    <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="http://localhost:8000/media/{{ post.miniature }}" alt="image">#}
					    <div class="media-body">

						    <h3 class="title mb-1"><a href="blog-post.html">{{ comment.post}}</a></h3>
                            <a href="http://3.16.215.121:8000/profile/{{ comment.user }}"><span class="date">{{ comment.user}}</span></a>
						    <div class="meta mb-1"><span class="date">{{ comment.created_at}}</span><span class="time"> 1 min read</span><span class="comment"><a href=""> 1 comments</a></span></div>
						    <div class="intro">{{ comment.content}}</div>
						    <a class="more-link" href="">Read more &rarr;</a>
					    </div><!--//media-body-->
				    </div><!--//media-->
			    </div><!--//item-->
                {% endfor %}


			    <nav class="blog-nav nav nav-justified my-5">
				  <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="#">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
{#				  <a class="nav-link-next nav-item nav-link rounded" href="blog-list.html">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>#}
				</nav>

		    </div>
	    </section>

templates/core/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Casinal</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- owl carousel style -->
   <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{%  static 'css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{%  static 'images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{%  static 'css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="{%  static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{%  static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
</head>

<body>
   <!--header section start -->
   <div class="header_section">
      <div class="header_bg">
         <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="{% url 'community:index' %}"><img src="https://i.ibb.co/M2sBzwg/logo.png"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'community:index' %} ">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="about.html">Comunidades</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="services.html">Noticias</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                  </ul>
                  <div class="call_section">
                     <ul>
                        <li><a href="#"><img src="{%  static 'images/fb-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/twitter-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/linkedin-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/instagram-icon.png' %}"></a></li>
                        <li>
                          {% if not user.is_anonymous %}
                        <a href="" class="btn">Perfil</a></li>
                    {% else %}
                                    <div class="header-btn d-none f-right d-lg-block">
                                    <a href="{% url 'users_app:user-register'%}" class="btn head-btn1">Registrarse</a>
                                    <a href="{% url 'users_app:user-login' %}" class="btn head-btn2">Acceder</a></li>
                    {% endif %}
                        <div class="donate_bt"><a href="#"><img src="{%  static 'images/search-icon.png' %}"></a></div>
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
      </div>
      <!--banner section start -->
      <div class="banner_section layout_padding">
         <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Espacio de tu artistas</h1>
                              <p class="banner_text">Ultimas actualziaciones</p>
                              <div class="btn_main">
                                   {% if user.is_anonymous %}
                                       <div class="about_bt active"><a href="{% url 'users_app:user-login' %}">Login</a></div>
                                 <div class="quote_bt"><a href="{% url 'users_app:user-register' %}">Registrarse </a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="{% url 'post:crer_post' %}">Crear Post</a></div>
                                 <div class="quote_bt"><a href="#">Explorar </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Red social de comunidades de tus artistas</h1>
                              <p class="banner_text">El mejor seguimiento de todos tus artistas favoritos en solo lugar</p>
                              <div class="btn_main">
                                 {% if user.is_anonymous %}
                                       <div class="about_bt active"><a href="{% url 'users_app:user-login' %}">Login</a></div>
                                 <div class="quote_bt"><a href="{% url 'users_app:user-register' %}">Registrarse </a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="{% url 'post:crer_post' %}">Crear Post</a></div>
                                 <div class="quote_bt"><a href="#">Explorar </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Red social de comunidades de tus artistas</h1>
                              <p class="banner_text">El mejor seguimiento de todos tus artistas favoritos en solo lugar</p>
                              <div class="btn_main">
                                 {% if user.is_anonymous %}
                                       <div class="about_bt active"><a href="{% url 'users_app:user-login' %}">Login</a></div>
                                 <div class="quote_bt"><a href="{% url 'users_app:user-register' %}">Registrarse </a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="{% url 'post:crer_post' %}">Crear Post</a></div>
                                 <div class="quote_bt"><a href="#">Explorar </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
               <i class="fa fa-arrow-left" style="font-size:24px"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
               <i class="fa fa-arrow-right" style="font-size:24px"></i>
            </a>
         </div>
      </div>
      <!--banner section end -->
   </div>
<section class="blog-list px-3 py-5 p-md-5"> Post
    {% for post in posts %}
		    <div class="container">
			    <div class="item mb-5">
				    <div class="media">
					    <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="http://3.16.215.121:8000/media/{{ post.miniature }}" alt="image">
					    <div class="media-body">
						    <h3 class="title mb-1"><a href="blog-post.html">{{ post.title}}</a></h3>
						    <div class="meta mb-1"><span class="date">{{ post.created_at}}</span><span class="time"> 5 min read</span><span class="comment"><a href="http://3.16.215.121:8000/comments/{{ post.slug }}"> 8 comments</a></span></div>
						    <div class="intro">{{ post.content}}</div>
						    <a class="more-link" href="blog-post.html">Read more &rarr;</a>
					    </div><!--//media-body-->
				    </div><!--//media-->
			    </div><!--//item-->
                {% endfor %}


			    <nav class="blog-nav nav nav-justified my-5">
				  <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="#">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
				  <a class="nav-link-next nav-item nav-link rounded" href="blog-list.html">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
				</nav>

		    </div>
	    </section>