chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('comunity.urls')),
    path('', include('posts.urls')),
    path('', include('comments.urls')),

    path('login/', auth_views.LoginView.as_view(), name='login'),
     
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'},
         name='logout')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comunity/urls.py
from django.urls import path
from comunity.views import CommunityList, CommunityDetail, CommunityCreateView

app_name = "community"

urlpatterns = [
    path('home/', CommunityList.as_view(), name='index'),
    path('comunidad/detail/<str:slug>', CommunityDetail.as_view(), name='comunidad_detail'),
    path('comunidad/crear', CommunityCreateView.as_view(), name='comunidad_crear'),
]

templates/community/create_community.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Casinal</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- owl carousel style -->
   <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{%  static 'css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{%  static 'images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{%  static 'css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="{%  static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{%  static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
</head>

<body>
   <!--header section start -->
   <div class="header_section">
      <div class="header_bg">
         <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="{% url 'community:index' %}"><img src="{%  static 'images/logo.png ' %}"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'community:index' %} ">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="about.html">Comunidades</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="services.html">Noticias</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                  </ul>
                  <div class="call_section">
                     <ul>
                        <li><a href="#"><img src="{%  static 'images/fb-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/twitter-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/linkedin-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/instagram-icon.png' %}"></a></li>
                        <div class="donate_bt"><a href="#"><img src="{%  static 'images/search-icon.png' %}"></a></div>
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
      </div>
       </div>
<br>
   <br>
   <br>
   <br>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">crear</button>
    </form>