chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('comunity.urls')),
    path('', include('posts.urls')),
    path('', include('comments.urls')),

    path('login/', auth_views.LoginView.as_view(), name='login'),
     
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'},
         name='logout')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comunity/urls.py
from django.urls import path
from comunity.views import CommunityList, CommunityDetail, CommunityCreateView

app_name = "community"

urlpatterns = [
    path('home/', CommunityList.as_view(), name='index'),
    path('comunidad/detail/<str:slug>', CommunityDetail.as_view(), name='comunidad_detail'),
    path('comunidad/crear', CommunityCreateView.as_view(), name='comunidad_crear'),
]

core/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from rest_framework.routers import DefaultRouter
from core.api import MessageModelViewSet, UserModelViewSet

router = DefaultRouter()
router.register(r'message', MessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')
app_name ="core"
urlpatterns = [
    path(r'api/v1/', include(router.urls)),

    path('', login_required(
        TemplateView.as_view(template_name='core/chat.html')), name='home'),

]

users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
    path(
        'user-verification/<pk>/', 
        views.CodeVerificationView.as_view(),
        name='user-verification',
    ),
    path(
        'profile/<shorname>/',
        views.UserProfileListView.as_view(),
        name='user-verification',
    ),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    username = models.CharField(max_length=10, unique=True)
    email = models.EmailField()
    nombres = models.CharField(max_length=30, blank=True)
    apellidos = models.CharField(max_length=30, blank=True)
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    codregistro = models.CharField(max_length=6, blank=True)
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email',]

    objects = UserManager()

    def get_short_name(self):
        return self.username
    
    def get_full_name(self):
        return self.nombres + ' ' + self.apellidos

users/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña'
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'username',
            'email',
            'nombres',
            'apellidos',
            'genero',
        )
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    username = forms.CharField(
        label='username',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'usernmae',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data


class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Actual'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva'
            }
        )
    )


class VerificationForm(forms.Form):
    codregistro = forms.CharField(required=True)


    def __init__(self, pk, *args, **kwargs):
        self.id_user = pk
        super(VerificationForm, self).__init__(*args, **kwargs)

    def clean_codregistro(self):
        codigo = self.cleaned_data['codregistro']

        if len(codigo) == 6:
            # verificamos si el codigo y el id de usuario son validos:
            activo = User.objects.cod_validation(
                self.id_user,
                codigo
            )
            if not activo:
                raise forms.ValidationError('el codigo es incorrecto')
        else:
            raise forms.ValidationError('el codigo es incorrecto')

users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic import (
    View,
    CreateView,ListView
)

from django.views.generic.edit import (
    FormView
)

from .forms import (
    UserRegisterForm, 
    LoginForm,
    UpdatePasswordForm,
    VerificationForm
)
#
from .models import User
# 
from .functions import code_generator


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = '/'

    def form_valid(self, form):
        # generamos el codigo
        codigo = code_generator()
        #
        usuario = User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            nombres=form.cleaned_data['nombres'],
            apellidos=form.cleaned_data['apellidos'],
            genero=form.cleaned_data['genero'],
            codregistro=codigo
        )
        # enviar el codigo al email del user
        asunto = 'Confrimacion d eemail'
        mensaje = 'Codigo de verificacion: ' + codigo
        email_remitente = 'neunapp.cursos@gmail.com'
        #
        # send_mail(asunto, mensaje, email_remitente, [form.cleaned_data['email'],])
        # redirigir a pantalla de valdiacion

        return HttpResponseRedirect(
            reverse(
                'community:index'
            )
        )



class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('community:index')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            username=usuario.username,
            password=form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)


class CodeVerificationView(FormView):
    template_name = 'users/verification.html'
    form_class = VerificationForm
    success_url = reverse_lazy('users_app:user-login')

    def get_form_kwargs(self):
        kwargs = super(CodeVerificationView, self).get_form_kwargs()
        kwargs.update({
            'pk': self.kwargs['pk'],
        })
        return kwargs

    def form_valid(self, form):
        #
        User.objects.filter(
            id=self.kwargs['pk']
        ).update(
            is_active=True
        )
        return super(CodeVerificationView, self).form_valid(form)


class UserProfileListView(ListView):
    template_name = 'users/profile.html'
    context_object_name = 'user'

    def get_queryset(self):
        # el codigo que yo queira
        area = self.kwargs['shorname']
        lista = User.objects.filter(
            username=area
        )
        return lista

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Casinal</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- owl carousel style -->
   <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{%  static 'css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{%  static 'images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{%  static 'css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="{%  static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{%  static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
</head>

<body>
   <!--header section start -->
   <div class="header_section">
      <div class="header_bg">
         <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="{% url 'community:index' %}"><img src="https://i.ibb.co/M2sBzwg/logo.png"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'community:index' %} ">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="about.html">Comunidades</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="services.html">Noticias</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                  </ul>
                  <div class="call_section">
                     <ul>
                        <li><a href="#"><img src="{%  static 'images/fb-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/twitter-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/linkedin-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/instagram-icon.png' %}"></a></li>
                        <div class="donate_bt"><a href="#"><img src="{%  static 'images/search-icon.png' %}"></a></div>
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
      </div>
       </div>
<br>
   <br>
   <br>
   <br>
    <h1>Acceder al sistema</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="" type="submit">Acceder</button>
    </form>
<a href="{% url 'users_app:user-register' %}"><button class="" type="submit">Registrarse</button></a>

templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Casinal</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- owl carousel style -->
   <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{%  static 'css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{%  static 'images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{%  static 'css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="{%  static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{%  static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
</head>

<body>
   <!--header section start -->
   <div class="header_section">
      <div class="header_bg">
         <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="{% url 'community:index' %}"><img src="https://i.ibb.co/M2sBzwg/logo.png"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'community:index' %} ">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="about.html">Comunidades</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="services.html">Noticias</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                  </ul>
                  <div class="call_section">
                     <ul>
                        <li><a href="#"><img src="{%  static 'images/fb-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/twitter-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/linkedin-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/instagram-icon.png' %}"></a></li>
                        <li>
                          {% if not user.is_anonymous %}
                        <a href="" class="btn">Perfil</a></li>
                    {% else %}
                                    <div class="header-btn d-none f-right d-lg-block">
                                    <a href="" class="btn head-btn1">Añadir Amigo</a>
                                    <a href="{% url 'core:home' %}" class="btn head-btn2">Enviar Mensaje</a></li>
                    {% endif %}
                        <div class="donate_bt"><a href="#"><img src="{%  static 'images/search-icon.png' %}"></a></div>
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
      </div>
      <!--banner section start -->
      <div class="banner_section layout_padding">
         <div id="my_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Red social de comunidades de tus artistas</h1>
                              <p class="banner_text">El mejor seguimiento de todos tus artistas favoritos en solo lugar</p>
                              <div class="btn_main">
                                   {% if user.is_anonymous %}
                                       <a href="" class="btn head-btn1">Añadir Amigo</a>
                                    <a href="{% url 'core:home' %}" class="btn head-btn2">Enviar Mensaje</a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="">Añadir amigo</a></div>
                                 <div class="quote_bt"><a href="{% url 'core:home' %}">Enviar Mensaje </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Red social de comunidades de tus artistas</h1>
                              <p class="banner_text">El mejor seguimiento de todos tus artistas favoritos en solo lugar</p>
                              <div class="btn_main">
                                 {% if user.is_anonymous %}
                                       <a href="" class="btn head-btn1">Añadir Amigo</a>
                                    <a href="{% url 'core:home' %}" class="btn head-btn2">Enviar Mensaje</a></div>
                    {% else %}

                                 <a href="" class="btn head-btn1">Añadir Amigo</a>
                                    <a href="{% url 'core:home' %}" class="btn head-btn2">Enviar Mensaje</a>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="banner_taital_main">
                        <div class="row">
                           <div class="col-md-6">
                              <h1 class="banner_taital">Red social de comunidades de tus artistas</h1>
                              <p class="banner_text">El mejor seguimiento de todos tus artistas favoritos en solo lugar</p>
                              <div class="btn_main">
                                 {% if user.is_anonymous %}
                                       <div class="about_bt active"><a href="{% url 'users_app:user-login' %}">Login</a></div>
                                 <div class="quote_bt"><a href="{% url 'users_app:user-register' %}">Registrarse </a></div>
                    {% else %}

                                 <div class="about_bt active"><a href="{% url 'community:comunidad_crear' %}">Crear Comunidad</a></div>
                                 <div class="quote_bt"><a href="#">Explorar </a></div>
                                  {% endif %}
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="image_1"><img src="https://phantom-elmundo.unidadeditorial.es/fcffe79e5833d475602741c7f8c50f39/crop/0x0/1110x740/resize/473/f/webp/assets/multimedia/imagenes/2023/01/12/16735304150144.jpg"></div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
               <i class="fa fa-arrow-left" style="font-size:24px"></i>
            </a>
            <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
               <i class="fa fa-arrow-right" style="font-size:24px"></i>
            </a>
         </div>
      </div>
      <!--banner section end -->
   </div>
{{ user }}

templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Casinal</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- owl carousel style -->
   <link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.0.0-beta.2.4/assets/owl.carousel.min.css" />
   <!-- bootstrap css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{%  static 'css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{%  static 'css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{%  static 'images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{%  static 'css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">
   <!-- owl stylesheets -->
   <link rel="stylesheet" href="{%  static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{%  static 'css/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
</head>

<body>
   <!--header section start -->
   <div class="header_section">
      <div class="header_bg">
         <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="logo" href="{% url 'community:index' %}"><img src="https://i.ibb.co/M2sBzwg/logo.png"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item active">
                        <a class="nav-link" href="{% url 'community:index' %} ">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="about.html">Comunidades</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="services.html">Noticias</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                  </ul>
                  <div class="call_section">
                     <ul>
                        <li><a href="#"><img src="{%  static 'images/fb-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/twitter-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/linkedin-icon.png' %}"></a></li>
                        <li><a href="#"><img src="{%  static 'images/instagram-icon.png' %}"></a></li>
                        <div class="donate_bt"><a href="#"><img src="{%  static 'images/search-icon.png' %}"></a></div>
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
      </div>
       </div>
<br>
   <br>
   <br>
   <br>

<
    <h1>Registar nuevo usuario</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>

templates/users/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Cambiar Contraseña: {{ user.get_full_name }}</h1>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Actualziar</button>
    </form>
</body>
</html>

templates/users/verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Verificacion de email</h1>
    <h3>Ingre el codigo de Verificacion:</h3>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Confirmar</button>
    </form>
</body>
</html>